"""Alter_default_value_of_status_column

Revision ID: 1e91ee1f8c0c
Revises: 200c4d7159fd
Create Date: 2025-07-12 17:05:14.833850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e91ee1f8c0c'
down_revision: Union[str, Sequence[str], None] = '200c4d7159fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
