"""Add_columns_to_large_language_models

Revision ID: 200c4d7159fd
Revises: 803e9d212f6f
Create Date: 2025-07-12 16:40:03.571450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '200c4d7159fd'
down_revision: Union[str, Sequence[str], None] = '803e9d212f6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('large_language_models', sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.add_column('large_language_models', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('large_language_models', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('large_language_models', 'status')
    op.drop_column('large_language_models', 'description')
    op.drop_column('large_language_models', 'provider')
    # ### end Alembic commands ###
