"""Add_composite_unique_constraint

Revision ID: f7baa5134456
Revises: 1e91ee1f8c0c
Create Date: 2025-07-13 00:21:36.022704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7baa5134456'
down_revision: Union[str, Sequence[str], None] = '1e91ee1f8c0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_large_language_models_name'), table_name='large_language_models')
    op.create_unique_constraint(None, 'large_language_models', ['name', 'model'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'large_language_models', type_='unique')
    op.create_index(op.f('ix_large_language_models_name'), 'large_language_models', ['name'], unique=False)
    # ### end Alembic commands ###
